name: flutter_application_1
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # =========================
  # CORE & UI
  # =========================
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.12.0
  custom_line_indicator_bottom_navbar: ^0.0.8
  intl: ^0.20.2

  # =========================
  # AUTH & FIREBASE
  # =========================
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  google_sign_in: ^6.2.2

  # =========================
  # STORAGE & STATE
  # =========================
  shared_preferences: ^2.5.4
  get: ^4.7.3

  # =========================
  # NETWORKING
  # =========================
  http: ^1.6.0
  http_parser: ^4.1.2
  json_annotation: ^4.9.0

  # =========================
  # IMAGE & CAMERA
  # =========================
  image_picker: ^1.0.7
  camera: ^0.11.0
  camera_platform_interface: ^2.12.3


  # =========================
  # POSE DETECTION (ML KIT)
  # =========================
  google_mlkit_pose_detection: ^0.11.0


  # =========================
  # TENSORFLOW LITE (AI MODEL)
  # =========================

  # TFLite (AMAN UNTUK DART 3)
  tflite_flutter: ^0.10.4
  tflite_flutter_helper: ^0.4.3+1


  # =========================
  # MATH (ANGLE & GEOMETRY)
  # =========================
  vector_math: ^2.1.4
  path_provider: ^2.1.0
  vibration: ^1.7.5

  # =========================
  # TEXT TO SPEECH (OPTIONAL)
  # =========================
  flutter_tts: ^3.8.3

  # =========================
  # PERMISSIONS
  # =========================
  permission_handler: ^11.0.1
  image: ^4.7.2
  image_picker_for_web: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/google_logo.png
    - assets/models/push-up/pushup_model.tflite
    - assets/models/push-up/meta.json
    - assets/models/push-up/scaler.json
    - assets/models/push-up/history.json
